export const allowedTypes = ["xmlhttprequest", "fetch"];

export const ignorePatterns = [
	"google-analytics.com",
	"googletagmanager.com",
	"facebook.com/tr",
	"mixpanel.com",
	"segment.io",
	"hotjar.com",
	"doubleclick.net",
	"sentry.io",
	"newrelic.com",
	"stats.g.doubleclick.net",
	"pixel.",
	"/collect?",
	"/track?",
	"mc.yandex.ru",
	"mc.yandex.com",
	"metrika.yandex",
	"adfox.ru",
	"top100.ru",
	"begun.ru",
	"rating.mail.ru",
	"counter.rambler.ru",
	"cnt.my.ru",
	"api.vk.com/method/stats",
	"tns-counter.ru",
	"criteo.com",
	"rtbhouse.com",
	"between.digital",
	"ads.adfox.ru",
	"ad.mail.ru",
	"recreativ.ru",
	"marketgid.com",
];
